background_opacity 0.70

font_family      Hack Nerd Font Mono Regular
bold_font        Hack Nerd Font Mono Bold
italic_font      Hack Nerd Font Mono Italic
bold_italic_font Hack Nerd Font Mono Bold Italic
font_size        12.0

# Tokyo Night
background            #1a1b26
foreground            #a9b1d6
selection_background  #283457
selection_foreground  #c0caf5
cursor                #c0caf5
cursor_text_color     #1a1b26

color0  #32344a
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #7aa2f7
color5  #ad8ee6
color6  #449dab
color7  #787c99
color8  #444b6a
color9  #ff7a93
color10 #b9f27c
color11 #ff9e64
color12 #7da6ff
color13 #bb9af7
color14 #0db9d7
color15 #acb0d0

confirm_os_window_close 0
